info:
  namespace: iaadditions

categories:
  iaadditions:
    enabled: true
    name: ItemsAdderAdditions 
    icon: iaadditions:iaadditions_block
    items:
    - iaadditions:chair
    - iaadditions:table
    - iaadditions:bed
    - iaadditions:double_bed
    - iaadditions:bunk_bed
    - iaadditions:night_stand_closed
    - iaadditions:iaadditions_block
    - iaadditions:stone_pebble_0
    - iaadditions:boogie_bomb
    - iaadditions:globe