info:
  namespace: iaadditions

entities:
  globe:
    model_folder: entity/globe
    type: ARMOR_STAND
    gravity: false
    ai: false

items:
  globe:
    name: "Globe"
    graphics:
      model: item/globe
    behaviours:
      complex_furniture:
        entity: globe
        solid: true
        fixed_rotation: true
        placement_offset:
          floor: -0.5
    events:
      placed_furniture:
        interact:
          play_animation:
            name: spin
          actionbar:
            text: "<white>📌 <bold>Location:</bold> <dark_gray>X:<gray>%player_x% <dark_gray>Y:<gray>%player_y% <dark_gray>Z:<gray>%player_z% <white>📌</white>"
  chair_template:
    name: ""
    graphics:
      model: iaadditions:furniture/chair
    template: true
    behaviours:
      furniture:
        entity: item_display
        display_transformation:
          transform: HEAD
        fixed_rotation: true
        opposite_direction: false
        solid: true
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.6
  chair:
    name: Chair
    variant_of: chair_template
    graphics:
      model: iaadditions:furniture/chair
    behaviours:
      connectable:
        type: stair
        default: iaadditions:chair
        straight: iaadditions:chair_center
        left: iaadditions:chair_left
        right: iaadditions:chair_right
        outer: iaadditions:chair_outer
        inner: iaadditions:chair_inner
  chair_center:
    variant_of: chair_template
    name: chair Center
    graphics:
      model: iaadditions:furniture/chair_center
  chair_right:
    variant_of: chair_template
    name: chair Right
    graphics:
      model: iaadditions:furniture/chair_right
  chair_outer:
    variant_of: chair_template
    name: chair Outer
    graphics:
      model: iaadditions:furniture/chair_outer
  chair_left:
    variant_of: chair_template
    name: chair Left
    graphics:
      model: iaadditions:furniture/chair_left
  chair_inner:
    variant_of: chair_template
    name: chair Inner
    graphics:
      model: iaadditions:furniture/chair_inner

  table_template:
    name: ""
    graphics:
      model: iaadditions:furniture/table
    template: true
    behaviours:
      furniture:
        entity: item_display
        display_transformation:
          transform: HEAD
        fixed_rotation: true
        opposite_direction: false
        solid: true
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  table:
    name: Table
    variant_of: table_template
    graphics:
      model: iaadditions:furniture/table
    behaviours:
      connectable:
        type: table
        default: iaadditions:table
        middle: iaadditions:table_center
        border: iaadditions:table_edge
        corner: iaadditions:table_corner
        end: iaadditions:table_end
        straight: iaadditions:table_straight
  table_center:
    variant_of: table_template
    name: Table Center
    graphics:
      model: iaadditions:furniture/table_center
  table_edge:
    variant_of: table_template
    name: Table Edge
    graphics:
      model: iaadditions:furniture/table_edge
  table_corner:
    variant_of: table_template
    name: Table Corner
    graphics:
      model: iaadditions:furniture/table_corner
  table_end:
    variant_of: table_template
    name: Table End
    graphics:
      model: iaadditions:furniture/table_end
  table_straight:
    variant_of: table_template
    name: Table Straight
    graphics:
      model: iaadditions:furniture/table_straight

  bed:
    name: Bed
    graphics:
      model: iaadditions:furniture/bed
    behaviours:
      bed:
        slots:
        - 1,0,0
      furniture:
        entity: item_display
        display_transformation:
          transform: HEAD
        fixed_rotation: true
        opposite_direction: false
        solid: true
        placeable_on:
          walls: false
          ceiling: false
          floor: true
        hitbox:
          height: 1
          length: 2
          width: 1
          length_offset: 0.5
  double_bed:
    name: Double Bed
    graphics:
      model: iaadditions:furniture/double_bed
    behaviours:
      bed:
        slots:
        - 1,0,0
        - 1,0,1
      furniture:
        entity: item_display
        display_transformation:
          transform: HEAD
        fixed_rotation: true
        opposite_direction: false
        solid: true
        placeable_on:
          walls: false
          ceiling: false
          floor: true
        hitbox:
          height: 1
          length: 2
          width: 2
          length_offset: 0.5
  bunk_bed:
    name: Bunk Bed
    graphics:
      model: iaadditions:furniture/bunk_bed
    behaviours:
      bed:
        slots:
        - 1,0,0
        - 1,1,0
      furniture:
        entity: item_display
        display_transformation:
          transform: HEAD
        fixed_rotation: true
        opposite_direction: false
        solid: true
        placeable_on:
          walls: false
          ceiling: false
          floor: true
        hitbox:
          height: 1
          length: 2
          width: 1
          length_offset: 0.5

  night_stand_closed:
    name: Night Stand 
    graphics:
      model: furniture/night_stand_closed
    behaviours:
      storage:
        type: storage
        rows: 3
        title: "Night Stand"
        open_variant: night_stand_open
        open_sound:
          name: block.barrel.open
          volume: 1.0 
          pitch: 1.0 
          category: MASTER 
        close_sound:
          name: block.barrel.close
          volume: 1.0 
          pitch: 1.0 
          category: MASTER 
      furniture:
        entity: item_display
        display_transformation:
          transform: HEAD
        fixed_rotation: true
        opposite_direction: true
        solid: true
        placeable_on:
          walls: false
          ceiling: false
          floor: true
        hitbox:
          height: 1
          length: 1
          width: 1
  night_stand_open:
    name: Night Stand 
    graphics:
      model: furniture/night_stand_open
    behaviours:
      furniture:
        entity: item_display
        display_transformation:
          transform: HEAD
        fixed_rotation: true
        opposite_direction: true
        solid: true
        placeable_on:
          walls: false
          ceiling: false
          floor: true
        hitbox:
          height: 1
          length: 1
          width: 1
